---
- name: install mysql
  yum: name=mariadb state=present

- name: check if MySQL root password is set
  shell: mysql -e 'select 1'
  register: result
  ignore_errors: True

- name: set MySQL root password
  shell: mysqladmin password {{ mysql_root_password }}
  when: result.rc==0

- name: put .my.cnf
  template: src=.my.cnf dest=/root/.my.cnf
