---
- name: install mysql
  yum: name=mariadb-server state=present

- name: start the service
  service: name=mariadb state=started enabled=yes

- name: check if MySQL root password is set
  command: mysql -e 'select 1' mysql
  become: yes
  become_user: mysql
  register: result
  ignore_errors: True
  changed_when: False

- name: set MySQL root password
  command: mysqladmin password {{ mysql_root_password }}
  when: result.rc==0

- name: put .my.cnf
  template: src=.my.cnf dest=/root/.my.cnf
